#!/bin/bash

# Script con due parametri: - directory D; - stringa S
# Per ogni sottodirectory di D:
# contare quanti file contengono almeno una volta la stringa S;
# stampare


if [[ $# -ne 2 ]]; then
    echo "Il numero di parametri passati allo script non è corretto" >&2
    exit 1
fi

directory=$1
string=$2

if [[ ! -d "$directory" || "$directory" != /* ]]; then
    echo "Il parametro passato allo script non rappresenta il percorso assoluto di una directory" >&2
    exit 1
fi

if [[ -z "$string" ]]; then
    echo "Il parametro passato allo script non rappresenta una stringa valida" >&2
    exit 1
fi

find "$directory" -mindepth 1 -type d | while read -r dir; do
    counter=0
    while read -r file; do
        if grep -q "$string" "$file"; then
            ((counter++))
        fi
    done < <(find "$dir" -type f)
    echo "Directory := '$dir' File trovati := '$counter'"
done
exit 0