#!/bin/bash

# Parametri: D, ovvero una directory; S, ovvero una stringa. Per ogni sottodirectory immediata di D:
# - contare quanti file contegono almeno una volta S
# stampare: directory -> numero_file

if [[ $# -ne 2 ]]; then
    echo "Il numero di parametri passati allo script non è corretto" >&2
    exit 1
fi

directory=$1
stringa=$2

if [[ ! -d "$directory" || "$directory" != /* ]]; then
    echo "Il parametro passato allo script non rappresenta il percorso assoluto di una directory" >&2
    exit 1
fi

if [[ -z "$stringa" ]]; then
    echo "Il parametro passato allo script non rappresenta una stringa valida" >&2
    exit 1
fi

while read -r dir; do
    number_files=0
    while read -r file; do
        if grep -q "$stringa" "$file"; then
            ((number_files++))
        fi
    done < <(find "$dir" -maxdepth 1 -type f)

    if [[ "$number_files" -gt 0 ]]; then
        echo "'$dir' -> '$number_files'"
    fi

done < <(find "$directory" -mindepth 1 -maxdepth 1 -type d)

exit 0

