#!/bin/bash


# Script con tre parametri: Directory, Number_integer_1, OUTFILE. Lo script deve:
# - cercare ricorsivamente tutti i file regolari;
# - selezionare solo quelli aventi almeno N righe;
# salvare nel file OUTFILE;

if [[ $# -ne 3 ]]; then
    echo "Il numero di parametri passati allo script non è corretto" >&2
    exit 1
fi

directory=$1
number_integer=$2
OUTFILE=$3

if [[ ! -d "$directory" || "$directory" != /* ]]; then
    echo "Il parametro passato allo script non rappresenta un percorso assoluto di una directory" >&2
    exit 1
fi

if [[ "$number_integer" -le 0 ]]; then
    echo "Il parametro passato allo script non rappresenta un numero intero valido da selezionare" >&2
    exit 1
fi

if [ -e "$OUTFILE" ] && [ ! -w "$OUTFILE" ]; then
    echo "Il file di output non è scrivibile"
    exit 1
fi

> "$OUTFILE"

find "$directory" -type f | while read -r file; do
    length_lines=$(wc -l < "$file")
    if [[ "$length_lines" -ge "$number_integer" ]]; then
        echo "'$file': '$length_lines'" >> "$OUTFILE"
    fi
done

exit 0