#!/bin/bash

# Scrivere uno script Bash che accetti tre parametri: directory assoluta D; estensione file .ext; intero positivo N.
# Lo script deve cercare ricorsivamente tutte le directory foglia di D; - per ogni directory trovata contare i file regolari con estensione .ext;
# - calcolare la dimensione totale occupata da tali file; - stampare solo le directory aventi più di N file

if [[ $# -ne 3 ]]; then
    echo "Il numero di parametri passati allo script non è corretto" >&2
    exit 1
fi

directory=$1
estensione=$2
positive_int=$3

if [[ ! -d "$directory" || "$directory" != /* ]]; then
    echo "Il parametro passato allo script non rappresenta una directory assoluta" >&2
    exit 1
fi

if [[ "$estensione" != .* ]]; then
    echo "Il parametro passato non rappresenta l'estensione di file richiesta" >&2
    exit 1
fi

if [[ "$positive_int" -lt 1 ]]; then
    echo "Il parametro passato allo script non rappresenta un intero positivo valido" >&2
    exit 1
fi

while read -r dir; do
    count_files=0
    count_size=0
    while read -r file; do
        ((count_files++))
        size=$(wc -c < "$file")
        ((count_size += size))
    done < <(find "$dir" -type f -name "*$estensione")
    if [[ "$count_files" -gt "$positive_int" ]]; then
        echo ""$dir" : "$count_files" files che soddisfano la condizione di ricerca ==> Size complessiva files = "$count_size"" 
    fi
done < <(find "$directory" -type d -links 2)
exit 0