#!/bin/bash

# Write a Bash script that accepts three parameters: A directory path D; A file extension; A positive integer N
# The script must recursively search the directory D for all leaf directories (i.e., directories that do not contain any subdirectories).
# For each leaf directory found, count the number of files having the extension specified as the second parameter.
# A leaf directory is selected only if the number of files with the given extension is greater than N.
# For every selected directory, print to standard output: its absolute path; the number of matching files.



if [[ $# -ne 3 ]]; then
    echo "Il numero di parametri passati allo script non è corretto" >&2
    exit 1
fi

directory=$1
extension=$2
num_integer=$3

if [[ ! -d "$directory" || "$directory" != /* ]]; then
    echo "Il parametro passato allo script non rappresenta il percorso assoluto di una cartella" >&2
    exit 1
fi

if [[ "$extension" != .* ]]; then
    echo "Il parametro passato allo script non rappresenta un'estensione di un file" >&2
    exit 1
fi

if [[ "$num_integer" -lt 0 ]]; then
    echo "Il parametro passato allo script non rappresenta un numero intero positivo" >&2
    exit 1
fi


find "$directory" -type d -links 2 | while read -r dir; do
    counter_file=0
    while read -r file; do
        ((counter_file++))
    done < <(find "$dir" -type f -maxdepth 1 -name "*$extension")
    if [[ "$counter_file" -gt "$num_integer" ]]; then
        printf "'$dir' -> Number_File = '$counter_file'\n"
    fi
done