#!/bin/bash

# Parametri: D; directory; N, un numero intero positivo.
# Trovare tutte le directory che contengono più di N file regolari direttamente al loro interno. Stampare: percorso assoluto, numero_file

if [[ $# -ne 2 ]]; then
    echo "Il numero di parametri passati allo script non è corretto" >&2
    exit 1
fi

directory=$1
positive_int=$2

if [[ ! -d "$directory" || "$directory" != /* ]]; then
    echo "Il parametro passato allo script non rappresenta il percorso assoluto di una directory" >&2
    exit 1
fi

if [[ "$positive_int" -lt 1 ]]; then
    echo "Il parametro passato allo script non rappresenta un numero intero positivo" >&2
    exit 1
fi

while read -r dir; do
    number_files=0
    while read -r file; do
        ((number_files++))
    done < <(find "$dir" -type f -mindepth 1 -maxdepth 1)
    if [[ "$number_files" -gt "$positive_int" ]]; then
            echo "'$dir' ==> Numero di files = '$number_files'"
    fi
done < <(find "$directory" -type d)
